sudo: required
services:
  - docker

before_install:
  - docker build -t maheshgprasad/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run maheshgprasad/react-test npm test -- --coverage

after_success:
  - docker build -t maheshgprasad/multi-client ./client
  - docker build -t maheshgprasad/multi-nginx ./nginx
  - docker build -t maheshgprasad/multi-server ./server
  - docker build -t maheshgprasad/multi-worker ./worker  

 #log in to the Docker CLI | credentials are to be stored on travis-ci project
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
 # Take those images and push them to docker hub
  - docker push maheshgprasad/multi-client
  - docker push maheshgprasad/multi-nginx
  - docker push maheshgprasad/multi-server
  - docker push maheshgprasad/multi-worker

deploy:
  provider: elasticbeanstalk
  region: ap-south-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-ap-south-1-865507620189
  bucket_path: docker-multi
  on: 
    branch: master
    access_key_id: $AWS_ACCESS_KEY
    secure_access_key:
      secure: $AWS_SECRET_KEY